/*
 * Copyright (c) 2024 Alexei Frolov
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the “Software”), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

syntax = "proto3";

import "google/protobuf/empty.proto";
import "event.proto";

package blert;

message ChallengeData {
  message TobRooms {
    optional TobRoom maiden = 1;
    optional TobRoom bloat = 2;
    optional TobRoom nylocas = 3;
    optional TobRoom sotetseg = 4;
    optional TobRoom xarpus = 5;
    optional TobRoom verzik = 6;
  }

  message TobRoom {
    Stage stage = 1;
    uint32 ticks_lost = 2;
    repeated string deaths = 3;
    repeated StageNpc npcs = 4;

    // Maiden 30-49
    repeated uint32 bloat_down_ticks = 50;
    repeated uint32 nylo_waves_stalled = 70;
    repeated uint32 sotetseg_maze_1_pivots = 90;
    repeated uint32 sotetseg_maze_2_pivots = 91;
    optional string sotetseg_maze_1_chosen = 92;
    optional string sotetseg_maze_2_chosen = 93;
    // Xarpus 110-129
    uint32 verzik_reds_count = 130;
  }

  message CoxRooms {
    optional CoxRoom tekton = 1;
    optional CoxRoom crabs = 2;
    optional CoxRoom ice_demon = 3;
    optional CoxRoom shamans = 4;
    optional CoxRoom vanguards = 5;
    optional CoxRoom thieving = 6;
    optional CoxRoom vasa = 7;
    optional CoxRoom vespula = 8;
    optional CoxRoom tightrope = 9;
    optional CoxRoom guardians = 10;
    optional CoxRoom mystics = 11;
    optional CoxRoom muttadile = 12;
    optional CoxRoom olm = 13;
  }

  message CoxRoom {
    Stage stage = 1;
    uint32 ticks_lost = 2;
    repeated string deaths = 3;
    repeated StageNpc npcs = 4;
  }

  message Colosseum {
    repeated ColosseumWave waves = 1;
    repeated uint32 all_handicaps = 2;
  }

  message ColosseumWave {
    Stage stage = 1;
    uint32 ticks_lost = 2;
    uint32 handicap_chosen = 3;
    repeated uint32 handicap_options = 4;
    repeated StageNpc npcs = 5;
  }

  message Inferno {
    repeated InfernoWave waves = 1;
  }

  message InfernoWave {
    Stage stage = 1;
    uint32 ticks_lost = 2;
    repeated StageNpc npcs = 3;
    uint32 ticks = 4;
    uint32 start_tick = 5;
  }

  message Mokhaiotl {
    repeated MokhaiotlDelve delves = 1;
  }

  message MokhaiotlDelve {
    Stage stage = 1;
    uint32 ticks_lost = 2;
    repeated StageNpc npcs = 3;
    uint32 delve = 4;
    uint32 challenge_ticks = 5;
    uint32 larvae_leaked = 6;
  }

  message StageNpc {
    uint32 spawn_npc_id = 1;
    fixed64 room_id = 2;
    uint32 spawn_tick = 3;
    uint32 death_tick = 4;
    Coords spawn_point = 5;
    Coords death_point = 6;

    // For future use.
    reserved 7 to 63;

    oneof type {
      google.protobuf.Empty basic = 64;
      Event.Npc.MaidenCrab maiden_crab = 65;
      Event.Npc.Nylo nylo = 66;
      Event.Npc.VerzikCrab verzik_crab = 67;
    }
  }

  string challenge_id = 1;
  oneof stage_data {
    TobRooms tob_rooms = 2;
    Colosseum colosseum = 3;
    Mokhaiotl mokhaiotl = 4;
    Inferno inferno = 5;
    CoxRooms cox_rooms = 6;
  }
}

message ChallengeEvents {
  repeated Event events = 1;

  // Metadata shared by all events.

  // Stage to which the events belong.
  Stage stage = 2;

  // Names of the players in the challenge.
  // Individual events index into this list to avoid storing repeated strings.
  repeated string party_names = 3;
}

// A split is a time recorded at some point of interest within a challenge.
enum SplitType {
  // Theatre of Blood splits.
  // All distinct ToB splits must have consecutive integer values, in the
  // order [entry mode, regular, hard mode] to allow for easy indexing on
  // mode.
  SPLIT_TYPE_TOB_ENTRY_CHALLENGE = 0;
  SPLIT_TYPE_TOB_REG_CHALLENGE = 1;
  SPLIT_TYPE_TOB_HM_CHALLENGE = 2;
  SPLIT_TYPE_TOB_ENTRY_OVERALL = 3;
  SPLIT_TYPE_TOB_REG_OVERALL = 4;
  SPLIT_TYPE_TOB_HM_OVERALL = 5;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN = 6;
  SPLIT_TYPE_TOB_REG_MAIDEN = 7;
  SPLIT_TYPE_TOB_HM_MAIDEN = 8;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN_70S = 9;
  SPLIT_TYPE_TOB_REG_MAIDEN_70S = 10;
  SPLIT_TYPE_TOB_HM_MAIDEN_70S = 11;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN_50S = 12;
  SPLIT_TYPE_TOB_REG_MAIDEN_50S = 13;
  SPLIT_TYPE_TOB_HM_MAIDEN_50S = 14;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN_30S = 15;
  SPLIT_TYPE_TOB_REG_MAIDEN_30S = 16;
  SPLIT_TYPE_TOB_HM_MAIDEN_30S = 17;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN_70S_50S = 18;
  SPLIT_TYPE_TOB_REG_MAIDEN_70S_50S = 19;
  SPLIT_TYPE_TOB_HM_MAIDEN_70S_50S = 20;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN_50S_30S = 21;
  SPLIT_TYPE_TOB_REG_MAIDEN_50S_30S = 22;
  SPLIT_TYPE_TOB_HM_MAIDEN_50S_30S = 23;
  SPLIT_TYPE_TOB_ENTRY_MAIDEN_30S_END = 24;
  SPLIT_TYPE_TOB_REG_MAIDEN_30S_END = 25;
  SPLIT_TYPE_TOB_HM_MAIDEN_30S_END = 26;
  SPLIT_TYPE_TOB_ENTRY_BLOAT = 27;
  SPLIT_TYPE_TOB_REG_BLOAT = 28;
  SPLIT_TYPE_TOB_HM_BLOAT = 29;
  SPLIT_TYPE_TOB_ENTRY_NYLO_ROOM = 30;
  SPLIT_TYPE_TOB_REG_NYLO_ROOM = 31;
  SPLIT_TYPE_TOB_HM_NYLO_ROOM = 32;
  SPLIT_TYPE_TOB_ENTRY_NYLO_CAP = 33;
  SPLIT_TYPE_TOB_REG_NYLO_CAP = 34;
  SPLIT_TYPE_TOB_HM_NYLO_CAP = 35;
  SPLIT_TYPE_TOB_ENTRY_NYLO_WAVES = 36;
  SPLIT_TYPE_TOB_REG_NYLO_WAVES = 37;
  SPLIT_TYPE_TOB_HM_NYLO_WAVES = 38;
  SPLIT_TYPE_TOB_ENTRY_NYLO_CLEANUP = 39;
  SPLIT_TYPE_TOB_REG_NYLO_CLEANUP = 40;
  SPLIT_TYPE_TOB_HM_NYLO_CLEANUP = 41;
  SPLIT_TYPE_TOB_ENTRY_NYLO_BOSS_SPAWN = 42;
  SPLIT_TYPE_TOB_REG_NYLO_BOSS_SPAWN = 43;
  SPLIT_TYPE_TOB_HM_NYLO_BOSS_SPAWN = 44;
  SPLIT_TYPE_TOB_ENTRY_NYLO_BOSS = 45;
  SPLIT_TYPE_TOB_REG_NYLO_BOSS = 46;
  SPLIT_TYPE_TOB_HM_NYLO_BOSS = 47;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG = 48;
  SPLIT_TYPE_TOB_REG_SOTETSEG = 49;
  SPLIT_TYPE_TOB_HM_SOTETSEG = 50;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_66 = 51;
  SPLIT_TYPE_TOB_REG_SOTETSEG_66 = 52;
  SPLIT_TYPE_TOB_HM_SOTETSEG_66 = 53;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_33 = 54;
  SPLIT_TYPE_TOB_REG_SOTETSEG_33 = 55;
  SPLIT_TYPE_TOB_HM_SOTETSEG_33 = 56;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_MAZE_1 = 57;
  SPLIT_TYPE_TOB_REG_SOTETSEG_MAZE_1 = 58;
  SPLIT_TYPE_TOB_HM_SOTETSEG_MAZE_1 = 59;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_MAZE_2 = 60;
  SPLIT_TYPE_TOB_REG_SOTETSEG_MAZE_2 = 61;
  SPLIT_TYPE_TOB_HM_SOTETSEG_MAZE_2 = 62;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_P2 = 63;
  SPLIT_TYPE_TOB_REG_SOTETSEG_P2 = 64;
  SPLIT_TYPE_TOB_HM_SOTETSEG_P2 = 65;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_P3 = 66;
  SPLIT_TYPE_TOB_REG_SOTETSEG_P3 = 67;
  SPLIT_TYPE_TOB_HM_SOTETSEG_P3 = 68;
  SPLIT_TYPE_TOB_ENTRY_XARPUS = 69;
  SPLIT_TYPE_TOB_REG_XARPUS = 70;
  SPLIT_TYPE_TOB_HM_XARPUS = 71;
  SPLIT_TYPE_TOB_ENTRY_XARPUS_EXHUMES = 72;
  SPLIT_TYPE_TOB_REG_XARPUS_EXHUMES = 73;
  SPLIT_TYPE_TOB_HM_XARPUS_EXHUMES = 74;
  SPLIT_TYPE_TOB_ENTRY_XARPUS_SCREECH = 75;
  SPLIT_TYPE_TOB_REG_XARPUS_SCREECH = 76;
  SPLIT_TYPE_TOB_HM_XARPUS_SCREECH = 77;
  SPLIT_TYPE_TOB_ENTRY_XARPUS_P2 = 78;
  SPLIT_TYPE_TOB_REG_XARPUS_P2 = 79;
  SPLIT_TYPE_TOB_HM_XARPUS_P2 = 80;
  SPLIT_TYPE_TOB_ENTRY_XARPUS_P3 = 81;
  SPLIT_TYPE_TOB_REG_XARPUS_P3 = 82;
  SPLIT_TYPE_TOB_HM_XARPUS_P3 = 83;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_ROOM = 84;
  SPLIT_TYPE_TOB_REG_VERZIK_ROOM = 85;
  SPLIT_TYPE_TOB_HM_VERZIK_ROOM = 86;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_P1_END = 87;
  SPLIT_TYPE_TOB_REG_VERZIK_P1_END = 88;
  SPLIT_TYPE_TOB_HM_VERZIK_P1_END = 89;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_REDS = 90;
  SPLIT_TYPE_TOB_REG_VERZIK_REDS = 91;
  SPLIT_TYPE_TOB_HM_VERZIK_REDS = 92;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_P2_END = 93;
  SPLIT_TYPE_TOB_REG_VERZIK_P2_END = 94;
  SPLIT_TYPE_TOB_HM_VERZIK_P2_END = 95;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_P2 = 96;
  SPLIT_TYPE_TOB_REG_VERZIK_P2 = 97;
  SPLIT_TYPE_TOB_HM_VERZIK_P2 = 98;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_P3 = 99;
  SPLIT_TYPE_TOB_REG_VERZIK_P3 = 100;
  SPLIT_TYPE_TOB_HM_VERZIK_P3 = 101;
  SPLIT_TYPE_TOB_ENTRY_NYLO_START = 102;
  SPLIT_TYPE_TOB_REG_NYLO_START = 103;
  SPLIT_TYPE_TOB_HM_NYLO_START = 104;
  SPLIT_TYPE_TOB_ENTRY_SOTETSEG_START = 105;
  SPLIT_TYPE_TOB_REG_SOTETSEG_START = 106;
  SPLIT_TYPE_TOB_HM_SOTETSEG_START = 107;
  SPLIT_TYPE_TOB_ENTRY_XARPUS_START = 108;
  SPLIT_TYPE_TOB_REG_XARPUS_START = 109;
  SPLIT_TYPE_TOB_HM_XARPUS_START = 110;
  SPLIT_TYPE_TOB_ENTRY_VERZIK_START = 111;
  SPLIT_TYPE_TOB_REG_VERZIK_START = 112;
  SPLIT_TYPE_TOB_HM_VERZIK_START = 113;

  // Colosseum wave times.
  SPLIT_TYPE_COLOSSEUM_CHALLENGE = 150;
  SPLIT_TYPE_COLOSSEUM_OVERALL = 151;
  SPLIT_TYPE_COLOSSEUM_WAVE_1 = 152;
  SPLIT_TYPE_COLOSSEUM_WAVE_2 = 153;
  SPLIT_TYPE_COLOSSEUM_WAVE_3 = 154;
  SPLIT_TYPE_COLOSSEUM_WAVE_4 = 155;
  SPLIT_TYPE_COLOSSEUM_WAVE_5 = 156;
  SPLIT_TYPE_COLOSSEUM_WAVE_6 = 157;
  SPLIT_TYPE_COLOSSEUM_WAVE_7 = 158;
  SPLIT_TYPE_COLOSSEUM_WAVE_8 = 159;
  SPLIT_TYPE_COLOSSEUM_WAVE_9 = 160;
  SPLIT_TYPE_COLOSSEUM_WAVE_10 = 161;
  SPLIT_TYPE_COLOSSEUM_WAVE_11 = 162;
  SPLIT_TYPE_COLOSSEUM_WAVE_12 = 163;
  SPLIT_TYPE_COLOSSEUM_WAVE_3_START = 164;
  SPLIT_TYPE_COLOSSEUM_WAVE_4_START = 165;
  SPLIT_TYPE_COLOSSEUM_WAVE_5_START = 166;
  SPLIT_TYPE_COLOSSEUM_WAVE_6_START = 167;
  SPLIT_TYPE_COLOSSEUM_WAVE_7_START = 168;
  SPLIT_TYPE_COLOSSEUM_WAVE_8_START = 169;
  SPLIT_TYPE_COLOSSEUM_WAVE_9_START = 170;
  SPLIT_TYPE_COLOSSEUM_WAVE_10_START = 171;
  SPLIT_TYPE_COLOSSEUM_WAVE_11_START = 172;
  SPLIT_TYPE_COLOSSEUM_WAVE_12_START = 173;

  // Mokhaiotl splits.
  SPLIT_TYPE_MOKHAIOTL_CHALLENGE = 200;
  SPLIT_TYPE_MOKHAIOTL_OVERALL = 201;
  SPLIT_TYPE_MOKHAIOTL_DELVE_1 = 202;
  SPLIT_TYPE_MOKHAIOTL_DELVE_2 = 203;
  SPLIT_TYPE_MOKHAIOTL_DELVE_3 = 204;
  SPLIT_TYPE_MOKHAIOTL_DELVE_4 = 205;
  SPLIT_TYPE_MOKHAIOTL_DELVE_5 = 206;
  SPLIT_TYPE_MOKHAIOTL_DELVE_6 = 207;
  SPLIT_TYPE_MOKHAIOTL_DELVE_7 = 208;
  SPLIT_TYPE_MOKHAIOTL_DELVE_8 = 209;
  SPLIT_TYPE_MOKHAIOTL_DELVE_3_START = 210;
  SPLIT_TYPE_MOKHAIOTL_DELVE_4_START = 211;
  SPLIT_TYPE_MOKHAIOTL_DELVE_5_START = 212;
  SPLIT_TYPE_MOKHAIOTL_DELVE_6_START = 213;
  SPLIT_TYPE_MOKHAIOTL_DELVE_7_START = 214;
  SPLIT_TYPE_MOKHAIOTL_DELVE_8_START = 215;

  // Inferno splits.
  SPLIT_TYPE_INFERNO_CHALLENGE = 220;
  SPLIT_TYPE_INFERNO_OVERALL = 221;
  SPLIT_TYPE_INFERNO_WAVE_9_START = 222;
  SPLIT_TYPE_INFERNO_WAVE_18_START = 223;
  SPLIT_TYPE_INFERNO_WAVE_25_START = 224;
  SPLIT_TYPE_INFERNO_WAVE_35_START = 225;
  SPLIT_TYPE_INFERNO_WAVE_42_START = 226;
  SPLIT_TYPE_INFERNO_WAVE_50_START = 227;
  SPLIT_TYPE_INFERNO_WAVE_57_START = 228;
  SPLIT_TYPE_INFERNO_WAVE_60_START = 229;
  SPLIT_TYPE_INFERNO_WAVE_63_START = 230;
  SPLIT_TYPE_INFERNO_WAVE_66_START = 231;
  SPLIT_TYPE_INFERNO_WAVE_67_START = 232;
  SPLIT_TYPE_INFERNO_WAVE_68_START = 233;
  SPLIT_TYPE_INFERNO_WAVE_69_START = 234;
  SPLIT_TYPE_INFERNO_WAVE_1_TIME = 235;
  SPLIT_TYPE_INFERNO_WAVE_2_TIME = 236;
  SPLIT_TYPE_INFERNO_WAVE_3_TIME = 237;
  SPLIT_TYPE_INFERNO_WAVE_4_TIME = 238;
  SPLIT_TYPE_INFERNO_WAVE_5_TIME = 239;
  SPLIT_TYPE_INFERNO_WAVE_6_TIME = 240;
  SPLIT_TYPE_INFERNO_WAVE_7_TIME = 241;
  SPLIT_TYPE_INFERNO_WAVE_8_TIME = 242;
  SPLIT_TYPE_INFERNO_WAVE_9_TIME = 243;
  SPLIT_TYPE_INFERNO_WAVE_10_TIME = 244;
  SPLIT_TYPE_INFERNO_WAVE_11_TIME = 245;
  SPLIT_TYPE_INFERNO_WAVE_12_TIME = 246;
  SPLIT_TYPE_INFERNO_WAVE_13_TIME = 247;
  SPLIT_TYPE_INFERNO_WAVE_14_TIME = 248;
  SPLIT_TYPE_INFERNO_WAVE_15_TIME = 249;
  SPLIT_TYPE_INFERNO_WAVE_16_TIME = 250;
  SPLIT_TYPE_INFERNO_WAVE_17_TIME = 251;
  SPLIT_TYPE_INFERNO_WAVE_18_TIME = 252;
  SPLIT_TYPE_INFERNO_WAVE_19_TIME = 253;
  SPLIT_TYPE_INFERNO_WAVE_20_TIME = 254;
  SPLIT_TYPE_INFERNO_WAVE_21_TIME = 255;
  SPLIT_TYPE_INFERNO_WAVE_22_TIME = 256;
  SPLIT_TYPE_INFERNO_WAVE_23_TIME = 257;
  SPLIT_TYPE_INFERNO_WAVE_24_TIME = 258;
  SPLIT_TYPE_INFERNO_WAVE_25_TIME = 259;
  SPLIT_TYPE_INFERNO_WAVE_26_TIME = 260;
  SPLIT_TYPE_INFERNO_WAVE_27_TIME = 261;
  SPLIT_TYPE_INFERNO_WAVE_28_TIME = 262;
  SPLIT_TYPE_INFERNO_WAVE_29_TIME = 263;
  SPLIT_TYPE_INFERNO_WAVE_30_TIME = 264;
  SPLIT_TYPE_INFERNO_WAVE_31_TIME = 265;
  SPLIT_TYPE_INFERNO_WAVE_32_TIME = 266;
  SPLIT_TYPE_INFERNO_WAVE_33_TIME = 267;
  SPLIT_TYPE_INFERNO_WAVE_34_TIME = 268;
  SPLIT_TYPE_INFERNO_WAVE_35_TIME = 269;
  SPLIT_TYPE_INFERNO_WAVE_36_TIME = 270;
  SPLIT_TYPE_INFERNO_WAVE_37_TIME = 271;
  SPLIT_TYPE_INFERNO_WAVE_38_TIME = 272;
  SPLIT_TYPE_INFERNO_WAVE_39_TIME = 273;
  SPLIT_TYPE_INFERNO_WAVE_40_TIME = 274;
  SPLIT_TYPE_INFERNO_WAVE_41_TIME = 275;
  SPLIT_TYPE_INFERNO_WAVE_42_TIME = 276;
  SPLIT_TYPE_INFERNO_WAVE_43_TIME = 277;
  SPLIT_TYPE_INFERNO_WAVE_44_TIME = 278;
  SPLIT_TYPE_INFERNO_WAVE_45_TIME = 279;
  SPLIT_TYPE_INFERNO_WAVE_46_TIME = 280;
  SPLIT_TYPE_INFERNO_WAVE_47_TIME = 281;
  SPLIT_TYPE_INFERNO_WAVE_48_TIME = 282;
  SPLIT_TYPE_INFERNO_WAVE_49_TIME = 283;
  SPLIT_TYPE_INFERNO_WAVE_50_TIME = 284;
  SPLIT_TYPE_INFERNO_WAVE_51_TIME = 285;
  SPLIT_TYPE_INFERNO_WAVE_52_TIME = 286;
  SPLIT_TYPE_INFERNO_WAVE_53_TIME = 287;
  SPLIT_TYPE_INFERNO_WAVE_54_TIME = 288;
  SPLIT_TYPE_INFERNO_WAVE_55_TIME = 289;
  SPLIT_TYPE_INFERNO_WAVE_56_TIME = 290;
  SPLIT_TYPE_INFERNO_WAVE_57_TIME = 291;
  SPLIT_TYPE_INFERNO_WAVE_58_TIME = 292;
  SPLIT_TYPE_INFERNO_WAVE_59_TIME = 293;
  SPLIT_TYPE_INFERNO_WAVE_60_TIME = 294;
  SPLIT_TYPE_INFERNO_WAVE_61_TIME = 295;
  SPLIT_TYPE_INFERNO_WAVE_62_TIME = 296;
  SPLIT_TYPE_INFERNO_WAVE_63_TIME = 297;
  SPLIT_TYPE_INFERNO_WAVE_64_TIME = 298;
  SPLIT_TYPE_INFERNO_WAVE_65_TIME = 299;
  SPLIT_TYPE_INFERNO_WAVE_66_TIME = 300;
  SPLIT_TYPE_INFERNO_WAVE_67_TIME = 301;
  SPLIT_TYPE_INFERNO_WAVE_68_TIME = 302;
  SPLIT_TYPE_INFERNO_WAVE_69_TIME = 303;
}
